---
# tasks file for wol

- name: Install ethtool
  ansible.builtin.package:
    name: ethtool
    state: present
  become: true
  become_user: root

- name: Deploy WOL systemd service
  ansible.builtin.template:
    src: wol.service.j2
    dest: "/etc/systemd/system/wol@.service"
    owner: root
    group: root
    mode: "0644"
  become: true
  become_user: root

- name: Force systemd to reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  become_user: root

- name: Check WOL support for interfaces
  ansible.builtin.shell: "ethtool {{ item }} | grep -q 'Wake-on: g'"
  ignore_errors: "{{ ansible_check_mode }}"
  changed_when: false
  failed_when: false
  loop: "{{ ansible_interfaces | select('search', '^(eth|en)') | list }}"
  register: wol_support
  become: true
  become_user: root

- name: Enable and start WOL services for supported interfaces
  ansible.builtin.service:
    name: "wol@{{ item.item }}"
    state: started
    enabled: true
  loop: "{{ wol_support.results }}"
  when: item.rc == 0
  become: true
  become_user: root
