---
# tasks file for wol

- name: Install ethtool
  ansible.builtin.package:
    name: ethtool
    state: present

- name: "Deploy wol systemd services"
  ansible.builtin.template:
    src: wol.service.j2
    dest: "/etc/systemd/system/wol-{{ item }}.service"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ ansible_interfaces | difference(['lo']) }}"
